name: Brew OwnTech Documentation Center
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout OwnTech Core repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/Core
          path: docs/core

      - name: Checkout OwnTech Control library repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/control_library
          path: docs/controlLibrary

      - name: Checkout OwnTech Examples repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/examples
          path: docs/examples

      - name: Checkout OwnTech Tutorials wiki repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/Tutorials.wiki
          path: docs/tutorials

      - name: Checkout OwnTech Twist repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/TWIST
          path: docs/twist
      
      - name: Checkout OwnTech Matlab repo
        uses: actions/checkout@v4
        with:
          repository: owntech-foundation/Owntech-Matlab
          path: docs/matlab

      - uses: ssciwr/doxygen-install@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install python packages
        run: pip install mkdocs-material mkdoxy pillow cairosvg
      - name: Print mkdocs version
        run: mkdocs --version
      - name: Publish docs
        run: mkdocs gh-deploy --force
